package com.dak.wrote.ui.theme


import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006689)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC3E8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2C)
val md_theme_light_secondary = Color(0xFF006D36)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF65FF99)
val md_theme_light_onSecondaryContainer = Color(0xFF00210C)
val md_theme_light_tertiary = Color(0xFF804893)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFAD7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF330045)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF001E30)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF001E30)
val md_theme_light_surfaceVariant = Color(0xFFDCE3E9)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787D)
val md_theme_light_inverseOnSurface = Color(0xFFE7F2FF)
val md_theme_light_inverseSurface = Color(0xFF003450)
val md_theme_light_inversePrimary = Color(0xFF7AD0FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006689)
val md_theme_light_surfaceTintColor = Color(0xFF006689)

val md_theme_dark_primary = Color(0xFF7AD0FF)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004C68)
val md_theme_dark_onPrimaryContainer = Color(0xFFC3E8FF)
val md_theme_dark_secondary = Color(0xFF42E180)
val md_theme_dark_onSecondary = Color(0xFF003919)
val md_theme_dark_secondaryContainer = Color(0xFF005227)
val md_theme_dark_onSecondaryContainer = Color(0xFF65FF99)
val md_theme_dark_tertiary = Color(0xFFEEB1FF)
val md_theme_dark_onTertiary = Color(0xFF4D1661)
val md_theme_dark_tertiaryContainer = Color(0xFF662F79)
val md_theme_dark_onTertiaryContainer = Color(0xFFFAD7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001E30)
val md_theme_dark_onBackground = Color(0xFFCBE6FF)
val md_theme_dark_surface = Color(0xFF001E30)
val md_theme_dark_onSurface = Color(0xFFCBE6FF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF001E30)
val md_theme_dark_inverseSurface = Color(0xFFCBE6FF)
val md_theme_dark_inversePrimary = Color(0xFF006689)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7AD0FF)
val md_theme_dark_surfaceTintColor = Color(0xFF7AD0FF)


